config/routes.rb
Rails.application.routes.draw do
  

  resources :places

  devise_for :users, controllers: { registrations: "registrations"}

  root 'pages#home'

end

app/models/place.rb
class Place < ActiveRecord::Base

	validates_presence_of :name
	validates_presence_of :user
	belongs_to :user
	
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  validates_presence_of :name
has_many :places

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @places = Place.all
  end

  def show
    respond_with(@place)
  end

  def new
    @place = Place.new
    respond_with(@place)
  end

  def edit
  end

  def create
    @place = current_user.places.new(place_params)
    @place.save
    respond_with(@place)
  end

  def update
    @place.update(place_params)
    respond_with(@place)
  end

  def destroy
    @place.destroy
    respond_with(@place)
  end

  private
    def set_place
      @place = Place.find(params[:id])
    end

    def place_params
      params.require(:place).permit(:name, :address, :description, :phone, :website)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

def  sign_up_params
params.require(:user).permit(:name, :email, :password)

	end

def account_update_params
params.require(:user).permit(:name, :email, :password, :currentpassword)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "DateTripper", root_path, class: "navbar-brand" %>
    </div>
 
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        
        <li> <%= link_to 'Places', places_path %> </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search for places">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li> <%= link_to "Settings", edit_user_registration_path %> </li>
        <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %> </li>
<% else %>
<li><%= link_to "Login", new_user_session_path %></li>
<li><%= link_to "Signup", new_user_registration_path %> </li>
        <% end%>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Places</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/header" %>
<div class="container">

	<% flash.each do |type, message| %>
	<div class="alert alert-info fade-in">
	<button class="close" data-dismiss="alert">x</button>
	<%= message %>
</div>
	<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/places/_form.html.erb
<%= simple_form_for(@place) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, required:true %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :phone %>
    <%= f.input :website %>
  
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing place</h1>

<%= render 'form' %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<h1>Listing places</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>

      <th>Phone</th>
      <th>Website</th>
   
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.address %></td>
        <td><%= place.phone %></td>
        <td><%= place.website %></td>
        
    </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user %>
<%= link_to 'New Place', new_place_path %>
<% end %>

app/views/places/new.html.erb
<h1>New place</h1>

<%= render 'form' %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<div class="row">
<div class="col-md-6">
  <h3><%= @place.name %></h3>
  <p>     <strong>Address: </strong><%= @place.address %> </p>
  <p>     <strong>Phone: </strong><%= @place.phone %> </p>
  <p>     <strong>Website: </strong><%= @place.website %> </p>
  <p>     <strong>Description: </strong><%= @place.description %> </p>

</div>

<div class="md-col-6">
  <h3> Reviews by People </h3>
  </div>
</div